### ISSUE TITLE
feature request: pretty based on .eslintrc

### ISSUE THREAD

**Issue by miguel-orange** [alizahid/atom-prettydiff#1]
feature request: pretty based on .eslintrc

**Comment by alizahid** [comment]
Hey @miguel-orange. Are you actually using this? I was just testing something out.

**Comment by miguel-orange** [comment]
Ha, mostly hunting for a good beautifier. I gotta say yours had some potential. I noticed it didn't translate es6 very well. Such as Import { named } from 'this';

**Comment by alizahid** [comment]
I'm using `Pretty Diff` in the background, but with more options than `atom-beautify` allowed.

Let me see what I can do.

**Comment by alizahid** [comment]
@miguel-orange Have you tried [Prettier](https://github.com/prettier/prettier)?
